Gpu rpo support
facebook/winterfell pull request #185
Opened 2023-04-14 12:14 UTC by andrewmilson

TODO: draft

2023-04-15 03:48 UTC, andrewmilson commented on prover/src/matrix/segments.rs
> +    pub fn new_with_buffer<E>(
Feel free to take it from here @irakliyk

2023-04-15 21:12 UTC, irakliyk requested changes
Looks great! Thank you! I left a few small comments inline - mostly related to API ergonomics.

2023-04-15 21:12 UTC, irakliyk commented on prover/src/matrix/segments.rs
> +            data.fill([B::ZERO; N]);
I would probably move this initialization into `new()` constructor. My thinking is that if we are using `new_with_buffer()`, the caller is responsible for initializing the buffer as they need.

2023-04-15 21:12 UTC, irakliyk commented on crypto/src/merkle/mod.rs
>  }
I don't mind this change, but I wonder if instead we could meet the requirements by adding another constructor. Maybe something like:
```Rust
pub fn from_raw_parts(nodes: Vec<H::Digest>, leaves: Vec<H::Digest>) -> Self
```

2023-04-15 21:22 UTC, irakliyk commented on prover/src/lib.rs
> +pub use matrix::{get_offsets, ColMatrix, RowMatrix, Segment};
Actually, let's do this as
```rust
pub mod matrix;
pub use matrix::{ColMatrix, RowMatrix};
```
So that we don't introduce a breaking change.

2023-04-16 03:57 UTC, irakliyk approved these changes
All looks good! Thank you!

2023-04-16 05:19 UTC, merged